# Generated by Django 3.2 on 2021-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210426_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pe_ratio',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='w52_high',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='w52_low',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ytd_change',
            field=models.CharField(max_length=10),
        ),
    ]
