# Generated by Django 3.2 on 2021-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210426_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
                ('is_item_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
